---
apiVersion: v1
kind: Pod
metadata:
  labels:
    job: build-service
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker/
      restartPolicy: Never
      resources:
        requests:
          cpu: "0.2"
          memory: "100Mi"
        limits:
          cpu: "0.5"
          memory: "500Mi"
  volumes:
  - name: kaniko-secret
    secret:
      name: kaniko-secret
