---
apiVersion: v1
kind: Pod
metadata:
  labels:
    job: build-service
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
      - /busybox/cat
      tty: true
      volumeMounts:
      - name: acr
        mountPath: /kaniko/.docker/
        readOnly: true
      restartPolicy: Never
      resources:
        requests:
          cpu: "0.2"
          memory: "100Mi"
        limits:
          cpu: "0.5"
          memory: "500Mi"
    - name: helm
      image: lachlanevenson/k8s-helm:v3.1.1
      imagePullPolicy: Always
      command:
      - cat
      tty: true
      resources:
        requests:
          cpu: "0.2"
          memory: "50Mi"
        limits:
          cpu: "0.2"
          memory: "200Mi"
  volumes:
  - name: acr
    projected:
      sources:
      - secret:
          name: kaniko-secret

